on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1

    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle config deployment true
        bundle install --jobs 8 --retry 3

    - name: build image
      run: docker build --tag test --file Dockerfile .

