on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1

    - name: Cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle config cache_all_platforms true
        bundle install --jobs 8 --retry 3
    - name: build image
      run: DOCKER_BUILDKIT=1 docker build --tag test --file Dockerfile .

    - name: run image
      run: docker run test
