on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: build image
      run: DOCKER_BUILDKIT=1 docker build --target=test -t beis-roda-test. --file Dockerfile

    - name: run image
      run: docker run test
